# ML2 — Feature Engineering (pandas, no Spark)

Same logic as the Spark version, using pandas `groupby` + `rolling` instead of SQL window functions. Fine for ~1.6M rows on a single machine.

**Rule:** every feature column uses only rows up to and including `t`. Nothing after `t` is touched until the label step (ML3).

In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# Adjust connection string to your SQL store
engine = create_engine("mysql+pymysql://root:root@localhost:3306/nopis")

df = pd.read_sql("SELECT * FROM fact_network_activity", engine)

# Ensure correct sort order: chronological within each grid
df = df.sort_values(["grid_id", "time_key"]).reset_index(drop=True)
df.head(10)

,grid_id,time_key,sms_in,sms_out,call_in,call_out,internet_activity,total_sms,total_calls,total_activity,internet_share
0,1,2013110100,2.0843,1.1047,0.5919,0.4293,57.7990,3.1890,1.0212,62.0092,0.932104
1,1,2013110101,1.1637,0.7700,0.1906,0.1942,44.0469,1.9337,0.3848,46.3654,0.949995
2,1,2013110102,0.4156,0.3004,0.0279,0.1360,41.2071,0.7160,0.1639,42.0870,0.979093
3,1,2013110103,1.1521,0.8957,0.0018,0.0261,33.0221,2.0478,0.0279,35.0978,0.940860
4,1,2013110104,0.3545,0.5112,0.0054,0.0261,31.3769,0.8657,0.0315,32.2741,0.972201
5,1,2013110105,0.1669,0.1954,0.0279,0.1842,34.8416,0.3623,0.2121,35.4160,0.983781
6,1,2013110106,0.2150,0.1158,0.2168,0.1579,35.4161,0.3308,0.3747,36.1216,0.980469
7,1,2013110107,0.8787,0.2447,0.2435,0.4946,42.9335,1.1234,0.7381,44.7950,0.958444
8,1,2013110108,3.6649,1.4366,1.1609,1.2768,59.8808,5.1015,2.4377,67.4200,0.888176
9,1,2013110109,4.3597,2.1153,2.9113,3.2219,71.1355,6.4750,6.1332,83.7437,0.849443

## Set up the grouped, ordered view

Everything below groups by `grid_id` first — this is the pandas equivalent of Spark's `PARTITION BY grid_id`. Each grid's 168 hourly rows are treated as their own independent timeline.

In [3]:
g = df.groupby("grid_id", sort=False)

## Column 1 — `avg_activity`
Mean of `total_activity` over the trailing 6 hours (t-5 to t), per grid.

In [4]:
df["avg_activity"] = g["total_activity"].transform(
    lambda s: s.rolling(window=6, min_periods=6).mean()
)
df[["grid_id", "time_key", "total_activity", "avg_activity"]].head(10)

   grid_id    time_key  total_activity  avg_activity
0        1  2013110100         62.0092           NaN
1        1  2013110101         46.3654           NaN
2        1  2013110102         42.0870           NaN
3        1  2013110103         35.0978           NaN
4        1  2013110104         32.2741           NaN
5        1  2013110105         35.4160     42.208250
6        1  2013110106         36.1216     37.893650
7        1  2013110107         44.7950     37.631917
8        1  2013110108         67.4200     41.854083
9        1  2013110109         83.7437     49.961733

## Column 2 — `activity_growth`
Recent 6h average minus the prior 6h baseline average (t-11 to t-6). Needs the baseline window computed separately, then shifted by 6 so it lines up with "6 hours before the recent window".

In [5]:
# baseline_avg at row t = avg_activity as it stood 6 rows earlier (i.e. the window t-11..t-6)
df["baseline_avg"] = g["avg_activity"].transform(lambda s: s.shift(6))
df["activity_growth"] = df["avg_activity"] - df["baseline_avg"]
df[["grid_id", "time_key", "avg_activity", "baseline_avg", "activity_growth"]].head(15)

    grid_id    time_key  avg_activity  baseline_avg  activity_growth
0         1  2013110100           NaN           NaN              NaN
1         1  2013110101           NaN           NaN              NaN
2         1  2013110102           NaN           NaN              NaN
3         1  2013110103           NaN           NaN              NaN
4         1  2013110104           NaN           NaN              NaN
5         1  2013110105     42.208250           NaN              NaN
6         1  2013110106     37.893650           NaN              NaN
7         1  2013110107     37.631917           NaN              NaN
8         1  2013110108     41.854083           NaN              NaN
9         1  2013110109     49.961733           NaN              NaN
10        1  2013110110     61.376667           NaN              NaN
11        1  2013110111     71.331967     42.208250        29.123717
12        1  2013110112     80.524100     37.893650        42.630450
13        1  2013110113     88.406383     37.631917        50.774467
14        1  2013110114     94.346450     41.854083        52.492367

## Column 3 — `active_hours`
Count of hours in the recent 6h window where `total_activity > 0`.

In [7]:
df["active_hours"] = g["total_activity"].transform(
    lambda s: (s > 0).rolling(window=6, min_periods=6).sum()
)
df[["grid_id", "time_key", "total_activity", "active_hours"]].head(10)

   grid_id    time_key  total_activity  active_hours
0        1  2013110100         62.0092           NaN
1        1  2013110101         46.3654           NaN
2        1  2013110102         42.0870           NaN
3        1  2013110103         35.0978           NaN
4        1  2013110104         32.2741           NaN
5        1  2013110105         35.4160           6.0
6        1  2013110106         36.1216           6.0
7        1  2013110107         44.7950           6.0
8        1  2013110108         67.4200           6.0
9        1  2013110109         83.7437           6.0

## Column 4 — `peak_ratio`
Max `total_activity` in the recent 6h window divided by the average of that same window.

In [8]:
df["peak_activity"] = g["total_activity"].transform(
    lambda s: s.rolling(window=6, min_periods=6).max()
)
df["peak_ratio"] = df["peak_activity"] / df["avg_activity"]
df[["grid_id", "time_key", "peak_activity", "avg_activity", "peak_ratio"]].head(10)

   grid_id    time_key  peak_activity  avg_activity  peak_ratio
0        1  2013110100            NaN           NaN         NaN
1        1  2013110101            NaN           NaN         NaN
2        1  2013110102            NaN           NaN         NaN
3        1  2013110103            NaN           NaN         NaN
4        1  2013110104            NaN           NaN         NaN
5        1  2013110105        62.0092     42.208250    1.469125
6        1  2013110106        46.3654     37.893650    1.223566
7        1  2013110107        44.7950     37.631917    1.190346
8        1  2013110108        67.4200     41.854083    1.610834
9        1  2013110109        83.7437     49.961733    1.676157

## Column 5 — `variability`
Standard deviation of `total_activity` over the recent 6h window.

In [9]:
df["variability"] = g["total_activity"].transform(
    lambda s: s.rolling(window=6, min_periods=6).std()
)
df["variability"] = df["variability"].fillna(0.0)
df[["grid_id", "time_key", "total_activity", "variability"]].head(10)

   grid_id    time_key  total_activity  variability
0        1  2013110100         62.0092     0.000000
1        1  2013110101         46.3654     0.000000
2        1  2013110102         42.0870     0.000000
3        1  2013110103         35.0978     0.000000
4        1  2013110104         32.2741     0.000000
5        1  2013110105         35.4160    10.997770
6        1  2013110106         36.1216     5.254137
7        1  2013110107         44.7950     4.763965
8        1  2013110108         67.4200    13.221186
9        1  2013110109         83.7437    20.922177

## Column 6 — `internet_share_avg`
Average of the existing `internet_share` column over the recent 6h window.

In [10]:
df["internet_share_avg"] = g["internet_share"].transform(
    lambda s: s.rolling(window=6, min_periods=6).mean()
)
df[["grid_id", "time_key", "internet_share", "internet_share_avg"]].head(10)

   grid_id    time_key  internet_share  internet_share_avg
0        1  2013110100        0.932104                 NaN
1        1  2013110101        0.949995                 NaN
2        1  2013110102        0.979093                 NaN
3        1  2013110103        0.940860                 NaN
4        1  2013110104        0.972201                 NaN
5        1  2013110105        0.983781            0.959672
6        1  2013110106        0.980469            0.967733
7        1  2013110107        0.958444            0.969141
8        1  2013110108        0.888176            0.953988
9        1  2013110109        0.849443            0.938752

## The `t+1` value (for the label — built in ML3, not here)
`next_total_activity` is `total_activity` shifted **backward** by one row within each grid — i.e. it pulls the *next* hour's value onto the current row. This is what ML3 will compare against the training-derived threshold. It must never be used as a feature.

In [11]:
df["next_total_activity"] = g["total_activity"].transform(lambda s: s.shift(-1))
df[["grid_id", "time_key", "total_activity", "next_total_activity"]].head(10)

   grid_id    time_key  total_activity  next_total_activity
0        1  2013110100         62.0092              46.3654
1        1  2013110101         46.3654              42.0870
2        1  2013110102         42.0870              35.0978
3        1  2013110103         35.0978              32.2741
4        1  2013110104         32.2741              35.4160
5        1  2013110105         35.4160              36.1216
6        1  2013110106         36.1216              44.7950
7        1  2013110107         44.7950              67.4200
8        1  2013110108         67.4200              83.7437
9        1  2013110109         83.7437             100.7637

## Assemble the final feature table

Drop rows that don't have a full 12h (6+6) history yet, and drop each grid's last row (no `t+1` to label).

In [12]:
df["row_num"] = g.cumcount() + 1  # 1-indexed position within each grid's timeline

feature_table = df[
    (df["row_num"] >= 12) &                 # full 6+6 history available
    (df["next_total_activity"].notna())     # has a t+1 to label
].copy()

feature_table = feature_table.rename(columns={"time_key": "feature_timestamp"})

output_cols = [
    "grid_id", "feature_timestamp",
    "avg_activity", "activity_growth", "active_hours",
    "peak_ratio", "variability", "internet_share_avg",
    "next_total_activity"
]

feature_table = feature_table[output_cols].reset_index(drop=True)
feature_table.head(10)

,grid_id,feature_timestamp,avg_activity,activity_growth,active_hours,peak_ratio,variability,internet_share_avg,next_total_activity
0,1,2013110111,71.331967,29.123717,6.0,1.412602,26.633648,0.883292,91.2744
1,1,2013110112,80.524100,42.630450,6.0,1.251348,20.965280,0.856580,92.0887
2,1,2013110113,88.406383,50.774467,6.0,1.139779,11.679930,0.838385,103.0604
3,1,2013110114,94.346450,52.492367,6.0,1.092361,6.995848,0.835685,99.2428
4,1,2013110115,96.929633,46.967900,6.0,1.063250,4.821376,0.841193,83.8200
5,1,2013110116,94.105683,32.729017,6.0,1.095156,6.716288,0.845601,89.8314
6,1,2013110117,93.219617,21.887650,6.0,1.105566,6.899499,0.851815,103.7075
7,1,2013110118,95.291800,14.767700,6.0,1.088315,7.980771,0.856880,92.5385
8,1,2013110119,95.366767,6.960383,6.0,1.087460,7.946706,0.859235,84.0115
9,1,2013110120,92.191950,-2.154500,6.0,1.124908,8.062555,0.856925,70.8246

## Row count sanity check

Expected rows ≈ `10000 grids × (168 hours − 11 dropped)` = `10000 × 157` = **1,570,000**, before accounting for any rows your pipeline already rejected.

In [13]:
print("Total feature rows:", len(feature_table))
print("Distinct grids:", feature_table["grid_id"].nunique())
print(feature_table.groupby("grid_id").size().describe())

Total feature rows: 1559994
Distinct grids: 10000
count    10000.0000
mean       155.9994
std          0.0600
min        150.0000
25%        156.0000
50%        156.0000
75%        156.0000
max        156.0000
dtype: float64

## Leakage test

Manually recompute `avg_activity` for one grid/hour directly from raw rows and confirm it matches. Then deliberately include `t+1` and confirm the value **changes** — proving the original calculation genuinely excludes it.

In [14]:
sample_grid = 1
sample_t = "2013110112"  # must have >= 12 prior hours

computed = feature_table.loc[
    (feature_table["grid_id"] == sample_grid) &
    (feature_table["feature_timestamp"] == sample_t),
    "avg_activity"
].values[0]

manual = df.loc[
    (df["grid_id"] == sample_grid) &
    (df["time_key"].between("2013110107", "2013110112")),  # t-5 .. t
    "total_activity"
].mean()

assert abs(computed - manual) < 1e-6, f"MISMATCH: computed={computed}, manual={manual}"
print(f"PASS: avg_activity matches manual calc ({computed:.4f})")

# Negative test: prove t+1 is NOT included -- including it should change the value
manual_with_leak = df.loc[
    (df["grid_id"] == sample_grid) &
    (df["time_key"].between("2013110107", "2013110113")),  # t-5 .. t+1 (leaked)
    "total_activity"
].mean()

assert abs(computed - manual_with_leak) > 1e-9, "FAIL: feature is identical even with t+1 included -- leakage test is not sensitive!"
print(f"PASS: including t+1 changes the value ({manual_with_leak:.4f}) -- confirms t+1 is correctly excluded")

PASS: avg_activity matches manual calc (80.5241)
PASS: including t+1 changes the value (82.1762) -- confirms t+1 is correctly excluded

## Persist the feature table

In [15]:
feature_table.to_sql(
    "network_feature_table",
    engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)
print("network_feature_table written.")

network_feature_table written.

In [16]:
# ML2 validation: check whether each grid has continuous hourly timestamps.

df["time_key"] = pd.to_datetime(df["time_key"], format="%Y%m%d%H")

g = df.sort_values(["grid_id", "time_key"]).groupby("grid_id")

time_diff = g["time_key"].diff().dropna()

print("Expected interval:", pd.Timedelta(hours=1))
print("Unexpected intervals:", (time_diff != pd.Timedelta(hours=1)).sum())

Expected interval: 0 days 01:00:00
Unexpected intervals: 5

In [17]:
# ML2 validation: inspect feature ranges for possible extreme values.

feature_cols = [
    "avg_activity",
    "activity_growth",
    "active_hours",
    "peak_ratio",
    "variability",
    "internet_share_avg"
]

print(feature_table[feature_cols].describe())

       avg_activity  activity_growth  active_hours    peak_ratio  \
count  1.559994e+06     1.559994e+06     1559994.0  1.559994e+06
mean   4.998997e+02     1.801184e+01           6.0  1.329315e+00
std    9.220931e+02     5.800673e+02           0.0  2.676044e-01
min    1.166633e+00    -2.626735e+04           6.0  1.002342e+00
25%    8.935963e+01    -5.917718e+01           6.0  1.140132e+00
50%    2.249794e+02     6.236825e+00           6.0  1.251819e+00
75%    5.132396e+02     7.992751e+01           6.0  1.441885e+00
max    3.528867e+04     2.903012e+04           6.0  4.543819e+00

        variability  internet_share_avg
count  1.559994e+06        1.559994e+06
mean   1.028158e+02        8.527650e-01
std    2.420707e+02        8.757058e-02
min    5.389400e-02        0.000000e+00
25%    1.534097e+01        7.965543e-01
50%    4.044228e+01        8.564522e-01
75%    9.905335e+01        9.230309e-01
max    1.360720e+04        1.000000e+00

In [18]:
# ML2 validation: check how strongly each feature relates to next-hour activity.

print(
    feature_table[
        feature_cols + ["next_total_activity"]
    ].corr()["next_total_activity"].sort_values()
)

internet_share_avg    -0.071633
peak_ratio            -0.013400
activity_growth        0.469839
variability            0.747160
avg_activity           0.895084
next_total_activity    1.000000
active_hours                NaN
Name: next_total_activity, dtype: float64